### ISSUE TITLE
Remove newlines from descriptions in v6.0 fragments

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/modis#19]
Most of the fragments have descriptions containing newlines, which seems bad. We should clean up the `description` fields (and any other long-text fields) to not contain newlines.

**Comment by pholleway** [comment]
This has been fixed for the completed v061 and will make sure to not include the newlines in new created fragments.

**Comment by gadomski** [comment]
Reopening as we haven't merge #33 yet, but will link to close when #33 is merged.

**Comment by pholleway** [comment]
Got it. I missed this comment applied to v6.0. I'll go through and remove the newlines in v6.0 too.
